apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  index.html: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Shhhhhhh!</title>
        <style>
           body {
           font-family: 'Arial', sans-serif;
           background-color: #f4f4f4;
           margin: 0;
           display: flex;
           justify-content: center;
           align-items: center;
           height: 100vh;
           }
           .container {
           text-align: center;
           }
           h1 {
           color: #333;
           }
        </style>
      </head>
      <body>
        <div class="container">
           <h1>UNIBO{4p1_d3c3pt10n_1s_g0d}</h1>
           <p>This is a super protected application!</p>
        </div>
      </body>
      </html>

