apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: python-data-generator
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: python-data-generator
    spec:
      completions: 5
      parallelism: 2
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: docker.io/unibo-cybersec/python-data-generator:v1
              name: python-data-generator
              env:
                - name: API_SERVER_URL
                  valueFrom:
                    configMapKeyRef:
                      name: api-config
                      key: API_SERVER_FULL
                - name: WORDLIST_PATH
                  valueFrom:
                    configMapKeyRef:
                      name: api-config
                      key: WORDLIST_PATH
              resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
