apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-server-deception
  name: python-server-deception
spec:
  ports:
  - port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: python-server-deception
  type: LoadBalancer
status:
  loadBalancer: {}
