apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: oauth-quarkus
  name: oauth-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth-quarkus
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oauth-quarkus
    spec:
      containers:
      - image: docker.io/unibo-cybersec/openapi-oauth-client:v1
        name: openapi-oauth-client
        ports:
        - containerPort: 8080
        resources: {}
status: {}
