apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: oauth-quarkus
  name: oauth-quarkus
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: oauth-quarkus
  type: LoadBalancer
status:
  loadBalancer: {}
