apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: oauth-quarkus
  name: oauth-quarkus
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: oauth-quarkus
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: oauth-quarkus
  name: oauth-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth-quarkus
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oauth-quarkus
    spec:
      containers:
      - image: docker.io/unibo-cybersec/openapi-oauth-client:v1
        name: openapi-oauth-client
        env:
        - name: QUARKUS_OIDC_AUTH_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: QUARKUS_OIDC_AUTH_SERVER_URL
        - name: QUARKUS_OIDC_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: CLIENT_ID
        - name: QUARKUS_OIDC_CREDENTIALS_SECRET
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: CLIENT_SECRET
        - name: QUARKUS_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: QUARKUS_LOG_LEVEL
        ports:
        - containerPort: 8080
        resources: {}
status: {}